SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ORDERS](
	[ORDERID] [int] IDENTITY(1,1) NOT NULL,
	[CUSTOMERID] [nvarchar](10) NULL,
	[ORDERDATE] [date] NULL,
	[DELIVERYEXPECTED] [date] NULL,
	[CONTAINSGIFT] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[ORDERID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PRODUCTS](
	[PRODUCTID] [int] IDENTITY(1,1) NOT NULL,
	[PRODUCTNAME] [nvarchar](50) NULL,
	[COLOUR] [nvarchar](20) NULL,
	[SIZE] [nvarchar](20) NULL,
PRIMARY KEY CLUSTERED 
(
	[PRODUCTID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
INSERT [dbo].[CUSTOMERS] ([CUSTOMERID], [FIRSTNAME], [LASTNAME], [EMAIL], [HOUSENO], [STREET], [TOWN], [POSTCODE]) VALUES (N'C34454', N'Bob', N'Marshal', N'bob@apl.com', N'1A', N'Uppingham Gate', N'Uppingham', N'LE159NY')
GO
INSERT [dbo].[CUSTOMERS] ([CUSTOMERID], [FIRSTNAME], [LASTNAME], [EMAIL], [HOUSENO], [STREET], [TOWN], [POSTCODE]) VALUES (N'R34788', N'Jack', N'Ross', N'jack@yahoo.com', N'4B', N'Strabokeway', N'Wortley', N'LS124NB')
GO
SET IDENTITY_INSERT [dbo].[ORDERITEMS] ON 
GO
INSERT [dbo].[ORDERITEMS] ([ORDERITEMID], [ORDERID], [PRODUCTID], [QUANTITY], [PRICE]) VALUES (1, 1, 1, 5, CAST(45.00 AS Decimal(9, 2)))
GO
INSERT [dbo].[ORDERITEMS] ([ORDERITEMID], [ORDERID], [PRODUCTID], [QUANTITY], [PRICE]) VALUES (2, 1, 2, 1, CAST(120.00 AS Decimal(9, 2)))
GO
INSERT [dbo].[ORDERITEMS] ([ORDERITEMID], [ORDERID], [PRODUCTID], [QUANTITY], [PRICE]) VALUES (3, 2, 3, 2, CAST(150.00 AS Decimal(9, 2)))
GO
SET IDENTITY_INSERT [dbo].[ORDERITEMS] OFF
GO
SET IDENTITY_INSERT [dbo].[ORDERS] ON 
GO
INSERT [dbo].[ORDERS] ([ORDERID], [CUSTOMERID], [ORDERDATE], [DELIVERYEXPECTED], [CONTAINSGIFT]) VALUES (1, N'C34454', CAST(N'2023-12-15' AS Date), CAST(N'2023-12-17' AS Date), 0)
GO
INSERT [dbo].[ORDERS] ([ORDERID], [CUSTOMERID], [ORDERDATE], [DELIVERYEXPECTED], [CONTAINSGIFT]) VALUES (2, N'C34454', CAST(N'2023-12-15' AS Date), CAST(N'2023-12-17' AS Date), 0)
GO
INSERT [dbo].[ORDERS] ([ORDERID], [CUSTOMERID], [ORDERDATE], [DELIVERYEXPECTED], [CONTAINSGIFT]) VALUES (3, N'R34788', CAST(N'2023-12-15' AS Date), CAST(N'2023-12-17' AS Date), 1)
GO
SET IDENTITY_INSERT [dbo].[ORDERS] OFF
GO
SET IDENTITY_INSERT [dbo].[PRODUCTS] ON 
GO
INSERT [dbo].[PRODUCTS] ([PRODUCTID], [PRODUCTNAME], [COLOUR], [SIZE]) VALUES (1, N'Tennis Ball', N'Yellow', N'S')
GO
INSERT [dbo].[PRODUCTS] ([PRODUCTID], [PRODUCTNAME], [COLOUR], [SIZE]) VALUES (2, N'Tennis Net', N'White', N'XL')
GO
INSERT [dbo].[PRODUCTS] ([PRODUCTID], [PRODUCTNAME], [COLOUR], [SIZE]) VALUES (3, N'Tennis Racket', N'White ', N'L')
GO
SET IDENTITY_INSERT [dbo].[PRODUCTS] OFF
GO
ALTER TABLE [dbo].[ORDERITEMS]  WITH CHECK ADD FOREIGN KEY([ORDERID])
REFERENCES [dbo].[ORDERS] ([ORDERID])
GO
ALTER TABLE [dbo].[ORDERITEMS]  WITH CHECK ADD FOREIGN KEY([PRODUCTID])
REFERENCES [dbo].[PRODUCTS] ([PRODUCTID])
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



GO